-- CreateEnum
CREATE TYPE "EstadoReserva" AS ENUM ('PENDIENTE', 'RESERVADO');

-- AlterTable
ALTER TABLE "PAQUETES" ADD COLUMN     "cupos_diarios" INTEGER NOT NULL DEFAULT 6,
ADD COLUMN     "dias_disponibles" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "fecha_fin" TIMESTAMP(3),
ADD COLUMN     "fecha_inicio" TIMESTAMP(3);

-- CreateTable
CREATE TABLE "CUPO_RESERVADO" (
    "id" SERIAL NOT NULL,
    "paquete_id" INTEGER NOT NULL,
    "usuario_id" INTEGER NOT NULL,
    "fecha" TIMESTAMP(3) NOT NULL,
    "estado" "EstadoReserva" NOT NULL DEFAULT 'PENDIENTE',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CUPO_RESERVADO_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "CUPO_RESERVADO" ADD CONSTRAINT "CUPO_RESERVADO_paquete_id_fkey" FOREIGN KEY ("paquete_id") REFERENCES "PAQUETES"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CUPO_RESERVADO" ADD CONSTRAINT "CUPO_RESERVADO_usuario_id_fkey" FOREIGN KEY ("usuario_id") REFERENCES "USUARIOS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
