-- AlterTable
ALTER TABLE "PAQUETES" ADD COLUMN     "activo" BOOLEAN NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE "SERVICIOS" ADD COLUMN     "activo" BOOLEAN NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE "TECNOLOGIAS" ADD COLUMN     "activo" BOOLEAN NOT NULL DEFAULT true;
