-- AlterTable
ALTER TABLE "ORDEN_PAQUETES" ADD COLUMN     "reserva_id" INTEGER;

-- AddForeignKey
ALTER TABLE "ORDEN_PAQUETES" ADD CONSTRAINT "ORDEN_PAQUETES_reserva_id_fkey" FOREIGN KEY ("reserva_id") REFERENCES "CUPO_RESERVADO"("id") ON DELETE SET NULL ON UPDATE CASCADE;
